config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :welfares, only: [:index, :new, :create]
  resources :groups, only: [:index, :new, :show, :create]
  resources :users, only: [:new, :create]
  resources :contributors, only: [:index, :new, :create, :show]
  
  root 'sessions#index'

  get 'menu', to: 'sessions#show'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: { message: 'is missing. please add a name' }, uniqueness: true
  validates :icon, presence: { message: 'is missing. please add an icon' }

  belongs_to :user
  has_many :categories
  has_many :welfares, through: :categories
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_login

  def index
    @groups = Group.all.order(name: :desc).includes(:user)
  end

  def new
    @group = current_user.groups.new

    @icons = [
      'https://cdn3.vectorstock.com/i/1000x1000/98/07/january-dates-flat-icon-with-long-shadow-vector-9319807.jpg',
      'https://cdn4.vectorstock.com/i/1000x1000/98/13/february-dates-flat-icon-with-long-shadow-vector-9319813.jpg',
      'https://cdn4.vectorstock.com/i/1000x1000/98/18/march-dates-flat-icon-with-long-shadow-vector-9319818.jpg',
      'https://cdn4.vectorstock.com/i/1000x1000/98/23/april-dates-flat-icon-with-long-shadow-vector-9319823.jpg',
      'https://cdn1.vectorstock.com/i/1000x1000/98/30/may-dates-flat-icon-with-long-shadow-vector-9319830.jpg',
      'https://cdn2.vectorstock.com/i/1000x1000/98/31/june-dates-flat-icon-with-long-shadow-vector-9319831.jpg',
      'https://cdn5.vectorstock.com/i/1000x1000/98/39/july-dates-flat-icon-with-long-shadow-vector-9319839.jpg',
      'https://cdn1.vectorstock.com/i/1000x1000/98/40/august-dates-flat-icon-with-long-shadow-vector-9319840.jpg',
      'https://cdn1.vectorstock.com/i/thumb-large/98/55/september-dates-flat-icon-with-long-shadow-vector-9319855.jpg',
      'https://cdn5.vectorstock.com/i/1000x1000/98/44/october-dates-flat-icon-with-long-shadow-vector-9319844.jpg',
      'https://cdn5.vectorstock.com/i/1000x1000/98/49/november-dates-flat-icon-with-long-shadow-vector-9319849.jpg',
      'https://cdn2.vectorstock.com/i/1000x1000/98/51/december-dates-flat-icon-with-long-shadow-vector-9319851.jpg'
    ]
  end

  def show
    @group = Group.find(params[:id])
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      flash[:alert] = @group.errors.full_messages.first
      redirect_to new_group_path
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/groups/_form.html.erb
<%= form_with model: @group do |form| %>
  <p id="alert"> <%= alert %> </p>
  <%= form.text_field :name, placeholder: 'Name', class: 'name-input' %>

  <div class="icons-field">
    <%= form.label 'Please select the group icon:', class: 'icon-title' %>
    <% @icons.each do |icon| %>
      <label>
        <%= form.radio_button(:icon, icon, class: 'icon-select') %>
        <%= image_tag(icon, class: 'icon') %>
      </label>
    <% end %>
  </div>

  <%= form.submit 'Save', class: 'action-btn' %>
<% end %>

app/views/groups/_group.html.erb
<div class="item-box">

  <% @groups.reverse_each do |group| %>
    <%= link_to raw("#{image_tag(group.icon, class: 'item-icon')}
      <p class='item-name'> #{group.name} </p>
      <p> Created on #{group.created_at.strftime('%b %d')} </p> 
      <p> by #{group.user.username} </p>"),
    group_path(group.id), class: 'item' %>
  <% end %>
</div>

app/views/groups/index.html.erb
<h1 class="nav-title">Groups</h1>

<p id="notice"><%= notice %></p>

<%= render 'group', group: @groups %>
<%= link_to raw('<span>New Group</span>'), new_group_path, class: 'action-btn' %>

app/views/groups/new.html.erb
<h1 class="nav-title">Create group</h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<h1 class="nav-title"><%= @group.name %></h1>

<%= render 'welfares/welfare', collection: @welfares = @group.welfares  %>
<%= link_to raw('<span>Add Welfare</span>'), new_welfare_path(group: @group.id), class: 'action-btn' %>