config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :welfares, only: [:index, :new, :create]
  resources :groups, only: [:index, :new, :show, :create]
  resources :users, only: [:new, :create]
  resources :contributors, only: [:index, :new, :create, :show]
  
  root 'sessions#index'

  get 'menu', to: 'sessions#show'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  validates :name, presence: true, length: { in: 3..100 }
  validates :phonenumber, presence: true, uniqueness: true, length: { is: 10 }
  validates :contributor_no, presence: true, uniqueness: true, length: { in: 4..10 }
  validates :icon, presence: true

  has_many :welfares, foreign_key: :contributor_no
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  before_action :require_login
  before_action :initialize_values

  def index
    @contributors = Contributor.all
  end

  def show
    @contributor = Contributor.find(params[:id])
    @welfares = Welfare.where(contributor_no: @contributor.contributor_no)
  end

  def new
    @contributor = Contributor.new
    @icons = [
      'https://www.flaticon.com/svg/static/icons/svg/3891/3891991.svg',
      'https://www.flaticon.com/svg/static/icons/svg/3135/3135789.svg'
    ]
  end

  def create
    @contributor = Contributor.create(contributor_params)

    if @contributor.save
      redirect_to contributors_path, notice: 'New welfare contributor created.'
    else
      flash.now[:alert] = @contributor.errors.full_messages.first
      render :new
    end
  end

  private

  def contributor_params
    params.require(:contributor).permit(:name, :phonenumber, :contributor_no, :icon)
  end

  def initialize_values
    @contributor = Contributor.new
    @icons = [
      'https://www.flaticon.com/svg/static/icons/svg/3891/3891991.svg',
      'https://www.flaticon.com/svg/static/icons/svg/3135/3135789.svg'
    ]
  end
end

app/helpers/contributor_helper.rb
module ContributorHelper
  def contributor_icon(contributor)
    if contributor.icon.empty?
      image_tag(current_user.icon, class: 'item-icon')
    else
      link_to image_tag(contributor.icon), contributor_path(contributor.id)
    end
  end
end

app/views/contributors/_contributor.html.erb
<div class="item-box">
  <% @contributors.order(:created_at).reverse_each do |contributor| %>
  <div class="item">
    <%= contributor_icon(contributor) %>
    <p class='item-name'> <%= contributor.name %> </p>
    <p> Phone: <b><%= contributor.phonenumber %></b></p>
    <p> Welfare No: <b><%= contributor.contributor_no %></b></p>
  </div>
  <% end %>
</div>

app/views/contributors/_form.html.erb
<%= form_with model: @contributor do |form| %>
  
  <p id="alert"> <%= alert %> </p>

  <%= form.text_field :contributor_no, placeholder: 'Welfare No.', class: 'name-input' %>

  <%= form.text_field :name, placeholder: 'Full name', class: 'name-input' %>

  <%= form.text_field :phonenumber, placeholder: 'Phone number', class: 'name-input' %>

  <div class="icons-field">
    <%= form.label 'Please select your profile icon:', class: 'icon-title' %>

    <% @icons.each do |icon| %>
      <label>
        <%= form.radio_button(:icon, icon, class: 'icon-select') %>
        <%= image_tag(icon, class: 'icon') %>
      </label>
    <% end %>
    
  </div>

  <%= button_to "Create contributor", contributors_path, method: :post, class: 'save-btn' %>
<% end %>

app/views/contributors/index.html.erb
<h1 class="nav-title">Contributors</h1>

<p id="notice"><%= notice %></p>

<%= render 'contributor', group: @contributors %>

<%= link_to raw("<span>New Contributor</span>"), new_contributor_path, class: 'action-btn-contributor' %>

app/views/contributors/new.html.erb
<h1 class="nav-title">Create contributor</h1>

<%= render 'form', group: @contributor %>

app/views/contributors/show.html.erb
<h1 class="nav-title"><%= @contributor.name %></h1>

<%= render 'welfares/welfare', collection: @welfares  %>